"""Built-in English/Russian copy for Zdorovo; no network translation at runtime."""

from __future__ import annotations

from typing import Any

UI_EN = {
    "Тёмная тема": "Dark theme",
    "Автотема": "Automatic theme",
    "ВАШ РИТМ": "YOUR RHYTHM",
    "Сегодня": "Today",
    "Обзор": "Overview",
    "Аналитика": "Analytics",
    "Настройки": "Settings",
    "Важно": "Important",
    "Дыхание": "Breathing",
    "Привычки": "Habits",
    "Достижения": "Achievements",
    "Уведомления": "Notifications",
    "Прочитать все": "Mark all read",
    "БЕРЕЖНЫЙ РАБОЧИЙ РИТМ": "A GENTLER WORK RHYTHM",
    "Работайте без перегруза": "Work without overload",
    "Паузы включаются только во время активной работы. Без слежки за содержимым экрана.": "Breaks run only during active work. Screen contents are never monitored.",
    "Напоминания на паузе · экранное время продолжает считаться": "Reminders paused · screen time is still counted",
    "Идёт демонстрация экрана · напоминания отложены, экранное время считается": "Screen sharing is active · reminders are delayed, screen time is still counted",
    "Считается общее активное время · по приложениям — после следующего входа в GNOME": "Total active time is counted · per-app tracking will be exact after the next GNOME login",
    "Экран сегодня": "Screen today",
    "активное время": "active time",
    "Паузы": "Breaks",
    "выполнено сегодня": "completed today",
    "Следующая пауза": "Next break",
    "по активному времени": "based on active time",
    "Ближайшие напоминания": "Upcoming reminders",
    "Дыхательная пауза": "Breathing pause",
    "Мягкий визуальный ритм без форсированных вдохов и обязательных задержек.": "A gentle visual rhythm without forced breaths or required breath holds.",
    "Мягкий старт": "Gentle start",
    "Спокойный короткий ритм без задержки дыхания": "A short, calm rhythm without breath holds",
    "Спокойный ритм": "Calm rhythm",
    "Пять минут с немного более длинным выдохом": "Five minutes with a slightly longer exhale",
    "Ровное дыхание": "Even breathing",
    "Одинаковая длительность вдоха и выдоха": "Equal inhale and exhale duration",
    "Выберите ритм": "Choose a rhythm",
    "Все режимы идут без обязательной задержки дыхания.": "Every mode works without required breath holds.",
    "Готовы начать": "Ready",
    "Сядьте удобно, расслабьте плечи и дышите без усилия.": "Sit comfortably, relax your shoulders and breathe without effort.",
    "Сбросить": "Reset",
    "завершённых сессий": "completed sessions",
    "За 7 дней": "Last 7 days",
    "Практика": "Practice",
    "за последние 7 дней": "over the last 7 days",
    "Автоматические дыхательные паузы": "Automatic breathing pauses",
    "Использует общий таймер активной работы и не показывается во время демонстрации экрана.": "Uses the shared active-work timer and stays hidden while your screen is being shared.",
    "Полезные привычки": "Healthy habits",
    "Небольшие дневные цели с локальной историей и необязательными напоминаниями.": "Small daily goals with local history and optional reminders.",
    "Добавить привычку": "Add habit",
    "дневных целей выполнено": "daily goals completed",
    "Активные": "Active",
    "привычки в вашем плане": "habits in your plan",
    "всего отметок": "total check-ins",
    "Прогулка или движение": "Walk or move",
    "Время без экрана вечером": "Screen-free time in the evening",
    "Полезная привычка": "Healthy habit",
    "Отменить отметку": "Undo",
    "Изменить": "Edit",
    "Самочувствие сейчас": "How you feel now",
    "Отметьте выраженность от 0 до 10. Это дневник, а не диагноз.": "Rate each symptom from 0 to 10. This is a journal, not a diagnosis.",
    "Головная боль": "Headache",
    "Усталость глаз": "Eye strain",
    "Поясница": "Lower back",
    "Голова": "Head",
    "Последняя отметка сохранена": "Last check-in is saved",
    "Пока нет отметок": "No check-ins yet",
    "Сохранить самочувствие": "Save check-in",
    "Сохранено только на этом компьютере": "Saved only on this computer",
    "Быстрый старт": "Quick start",
    "БЛИЖАЙШЕЕ ПО ПЛАНУ": "NEXT ON YOUR SCHEDULE",
    "Не ждите таймера, если пауза нужна уже сейчас.": "Do not wait for the timer when you need a break now.",
    "Глаза": "Eyes",
    "Размяться": "Move",
    "Шея": "Neck",
    "Экранное время": "Screen time",
    "Локальная статистика: ничего не отправляется в интернет.": "Local statistics: nothing is sent to the internet.",
    "Последние 7 дней": "Last 7 days",
    "Активность за день": "Activity by day",
    "Почасовое распределение экранного времени по приложениям.": "Hourly screen-time distribution by application.",
    "Каждый столбец — два часа. Цвет показывает приложение, число сверху — общее активное время.": "Each bar covers two hours. Colour identifies the application; the number above is total active time.",
    "Каждый столбец — один час. Цвет показывает приложение, число сверху — общее активное время. График можно прокручивать по горизонтали.": "Each bar covers one hour. Colour identifies the application; the number above is total active time. Scroll horizontally to see the whole day.",
    "Приложения": "Applications",
    "Нажмите на глаз, чтобы убрать приложение из недельного и дневного графиков.": "Use the eye button to remove an application from both the weekly and daily charts.",
    "Упражнения за 7 дней": "Exercises over 7 days",
    "В упражнениях": "Exercise time",
    "Завершено": "Completed",
    "Отложено": "Postponed",
    "Без откладывания": "Without postponing",
    "Здесь появятся выполненные упражнения": "Completed exercises will appear here",
    "Время начнёт считаться после кнопки «Начать упражнение»": "Time starts after you press “Start exercise”",
    "Самочувствие и нагрузка": "Wellbeing and workload",
    "Самочувствие сегодня": "Wellbeing today",
    "Самочувствие за день": "Wellbeing by day",
    "Дневные отметки рядом с экранным временем и выполненными паузами.": "Daily check-ins alongside screen time and completed breaks.",
    "Последняя отметка": "Latest check-in",
    "Паузы сегодня": "Breaks today",
    "Упражнения сегодня": "Exercise today",
    "Экран за день": "Screen time",
    "Паузы за день": "Breaks",
    "Упражнения за день": "Exercise time",
    "Здесь появится история самочувствия": "Your wellbeing history will appear here",
    "Сделайте первую отметку на главном экране": "Add your first check-in on the Today page",
    "Статистика появится после нескольких минут работы": "Statistics will appear after a few minutes of work",
    "Сбор уже работает в фоне": "Collection is already running in the background",
    "Ваш режим — ваши правила": "Your routine, your rules",
    "Базовый профиль уже настроен. Меняйте только то, что действительно помогает.": "The base routine is ready. Change only what genuinely helps.",
    "Оформление": "Appearance",
    "Выберите тему вручную или переключайте её по расписанию": "Choose a theme manually or switch it on a schedule",
    "Светлая тема с": "Light theme from",
    "Тёмная тема с": "Dark theme from",
    "Основной режим": "Main routine",
    "Рекомендованный профиль — всё уже включено": "Recommended profile — everything is already enabled",
    "Дополнительно": "Optional",
    "Эти активности не включаются без вашего решения": "These activities stay off until you enable them",
    "Отдых для глаз": "Eye rest",
    "Чередует даль, смену фокуса и отдых": "Alternates distance, focus changes and rest",
    "Общая разминка": "General movement",
    "Шесть видов пауз по очереди": "Six rotating break routines",
    "Шея и плечи": "Neck and shoulders",
    "Шесть мягких комплексов по очереди": "Six gentle rotating routines",
    "Капли для глаз": "Eye drops",
    "Настройте строго по своей схеме": "Set only according to your own schedule",
    "Поясница и таз": "Lower back and hips",
    "Пять комплексов; выключено по умолчанию": "Five routines; off by default",
    "Кисти и предплечья": "Hands and forearms",
    "Спокойное дыхание": "Calm breathing",
    "Пять вариантов; выключено по умолчанию": "Five options; off by default",
    "Проверить жажду": "Check thirst",
    "Без навязанной нормы жидкости": "No imposed water target",
    "Поведение": "Behaviour",
    "Полный экран": "Fullscreen",
    "Не беспокоить поверх видео и презентаций": "Do not interrupt videos and presentations",
    "Бездействие": "Idle time",
    "Когда остановить экранное время": "When screen-time counting should stop",
    "Демонстрация экрана": "Screen sharing",
    "Не открывать напоминания на созвоне; статистика продолжит считаться": "Do not show reminders while sharing; statistics will keep counting",
    "Звуковые подсказки": "Sound cues",
    "Сигнал в начале, при смене этапа и в конце упражнения": "A sound at the start, between steps and at the end",
    "Проверить звук": "Test sound",
    "Перенос данных": "Data transfer",
    "Экспортирует аналитику, достижения и все настройки. Импорт полностью заменяет текущие данные.": "Exports analytics, achievements and all settings. Import completely replaces the current data.",
    "Экспортировать": "Export",
    "Импортировать": "Import",
    "Напомнить позже": "Remind me later",
    "Через сколько минут снова показать отложенное напоминание": "When to show a postponed reminder again",
    "Оценка самочувствия": "Wellbeing check-in",
    "До трёх напоминаний в день; после ответа больше не беспокоит": "Up to three reminders a day; stops after you respond",
    "Все данные остаются на этом компьютере": "All data stays on this computer",
    "Сохраняются только название приложения, длительность и отметки о паузах. Снимков экрана нет.": "Only the application name, duration and break events are stored. No screenshots.",
    "Проверить": "Preview",
    "Это важно": "Important information",
    "Приложение помогает менять рабочие привычки, но не заменяет профессиональную консультацию.": "The app helps with work habits but does not replace professional advice.",
    "Когда лучше обратиться за советом": "When to seek advice",
    "Повторяющиеся, необычные или усиливающиеся симптомы лучше обсуждать с квалифицированным врачом. Если внезапно возникли выраженная слабость, онемение, нарушение речи, зрения или координации — обращайтесь за экстренной помощью.": "Recurring, unusual or worsening symptoms are best discussed with a qualified clinician. Seek urgent help for sudden marked weakness, numbness, speech, vision or coordination problems.",
    "Движение": "Movement",
    "Выбирайте медленную комфортную амплитуду без рывков и давления. Индивидуальный комплекс лучше согласовать с врачом.": "Use a slow, comfortable range without jerking or pressure. Discuss an individual routine with a clinician.",
    "Самочувствие": "Wellbeing",
    "Если активность вызывает неприятные ощущения, остановитесь. Повторяющиеся симптомы лучше обсудить с врачом.": "Stop if an activity causes discomfort. Discuss recurring symptoms with a clinician.",
    "Глаза и средства ухода": "Eyes and eye care",
    "Перерывы помогают снизить нагрузку, но не заменяют профессиональную оценку. Индивидуальный режим лучше согласовать с врачом.": "Breaks may reduce strain but do not replace professional assessment. Discuss an individual schedule with a clinician.",
    "Напомнить через 5 минут": "Remind me in 5 minutes",
    "Начать упражнение": "Start exercise",
    "Пауза": "Pause",
    "Продолжить": "Resume",
    "Завершить": "Finish",
    "Готово": "Done",
    "Таймер приостановлен": "Timer paused",
    "Упражнение завершено": "Exercise complete",
    "Нажмите «Начать упражнение» — этапы и время приложение отсчитает само.": "Press “Start exercise” — the app will time every step for you.",
}


META_EN: dict[str, dict[str, Any]] = {
    "eyes": {
        "title": "Eye reset",
        "eyebrow": "A short visual break",
        "note": "Stop if this causes discomfort. Discuss recurring symptoms with a clinician.",
        "steps": [
            "Look away from the screen at an object at least 6 metres away.",
            "Let your focus relax; do not force clarity.",
            "Blink slowly and fully 8–10 times.",
        ],
        "variants": [
            {
                "title": "Give your eyes distance",
                "eyebrow": "20 seconds without near focus",
                "duration_seconds": 20,
                "step_seconds": [14, 6],
                "steps": [
                    "Turn away from the screen and look at something at least 6 metres away.",
                    "Keep your gaze relaxed and blink slowly 8–10 times.",
                ],
            },
            {
                "title": "Gentle focus change",
                "eyebrow": "45 seconds of changing distance",
                "duration_seconds": 45,
                "step_seconds": [10, 5, 10, 5, 15],
                "steps": [
                    "Look into the distance without forcing focus.",
                    "Look at an object at comfortable arm’s length.",
                    "Return your gaze to the distance.",
                    "Look at the nearer object once more.",
                    "Return to the distant object and finish with slow, complete blinks.",
                ],
            },
            {
                "title": "Quiet rest away from the screen",
                "eyebrow": "Eye rest without near focus",
                "duration_seconds": 60,
                "step_seconds": [20, 20, 20],
                "steps": [
                    "Close your eyes gently without squeezing or pressing on them.",
                    "Open your eyes and look calmly into the distance.",
                    "Blink slowly 8 times and stay away from the screen a little longer.",
                ],
            },
        ],
    },
    "general": {
        "title": "Active break",
        "eyebrow": "A different gentle routine each time",
        "note": "Move only within a comfortable range. Discuss recurring or worsening symptoms with a clinician.",
        "steps": [
            "Walk at an easy pace.",
            "Draw your shoulder blades together gently.",
            "Rise onto your toes while holding stable support.",
            "Finish in a relaxed standing posture.",
        ],
        "variants": [
            {
                "title": "Steps and posture change",
                "eyebrow": "Light movement",
                "duration_seconds": 300,
                "steps": [
                    "Walk at an easy pace for 2–3 minutes.",
                    "Rise onto your toes 10 times while holding stable support.",
                    "Stand comfortably or continue walking for the rest of the break.",
                ],
            },
            {
                "title": "Move the upper body",
                "eyebrow": "No sudden movement",
                "duration_seconds": 180,
                "steps": [
                    "Lower your shoulders and draw your shoulder blades together 8 times.",
                    "Bend your elbows and slowly open your arms 6 times.",
                    "Shake out your hands and fully open your fingers 10 times.",
                    "Finish with easy walking.",
                ],
            },
            {
                "title": "Legs and stability",
                "eyebrow": "Stay near support",
                "duration_seconds": 180,
                "steps": [
                    "Shift your weight from one leg to the other 8 times.",
                    "Do 5 slow sit-to-stands if comfortable.",
                    "Rise onto your toes 10 times while holding support.",
                    "Walk for the rest of the break.",
                ],
            },
            {
                "title": "Calm full-body reset",
                "eyebrow": "Gentle whole-body movement",
                "duration_seconds": 300,
                "steps": [
                    "Walk for about two minutes.",
                    "Draw your shoulder blades together 8 times without lifting your shoulders.",
                    "Make 5 very small standing back extensions if comfortable.",
                    "Rise onto your toes 10 times and finish with natural breathing.",
                ],
            },
            {
                "title": "Feet and balance",
                "eyebrow": "Stay close to support",
                "duration_seconds": 240,
                "steps": [
                    "Shift your weight from foot to foot 8 times.",
                    "Rise onto your toes 8 times.",
                    "Gently lift your toes 8 times while keeping your torso upright.",
                    "Finish with easy walking.",
                ],
            },
            {
                "title": "Chair, shoulder blades and walking",
                "eyebrow": "Change the load across the body",
                "duration_seconds": 240,
                "steps": [
                    "Do 5 slow sit-to-stands if comfortable.",
                    "Lower your shoulders and draw your shoulder blades together 8 times.",
                    "Fully open and relax your fingers 10 times.",
                    "Finish with easy walking.",
                ],
            },
        ],
    },
    "neck": {
        "title": "Gentle neck reset",
        "eyebrow": "No jerking or forcing",
        "note": "Do not circle your neck or pull with your hands. Stop if uncomfortable and seek professional advice when needed.",
        "steps": [
            "Sit tall and gently draw your chin backwards.",
            "Turn your head within a comfortable range.",
            "Tilt one ear towards each shoulder without lifting the shoulders.",
            "Lower and gently set your shoulder blades.",
        ],
        "variants": [
            {
                "title": "Bring your head back over your shoulders",
                "eyebrow": "Posture reset",
                "duration_seconds": 180,
                "steps": [
                    "Sit with back support, lower your shoulders and look ahead.",
                    "Gently draw your chin backwards 5 times without looking down.",
                    "Draw your shoulder blades back and slightly down 6 times.",
                    "Stand and walk gently for the rest of the break.",
                ],
            },
            {
                "title": "Easy neck turns",
                "eyebrow": "Comfortable mobility",
                "duration_seconds": 180,
                "steps": [
                    "Sit tall, relax your jaw and keep a slight chin tuck.",
                    "Turn right and left 3 times, only to a comfortable limit.",
                    "Tilt one ear towards each shoulder 3 times without using your hand.",
                    "Return to neutral and let your shoulders settle down 5 times.",
                ],
            },
            {
                "title": "Release the shoulder girdle",
                "eyebrow": "Shoulders and shoulder blades",
                "duration_seconds": 180,
                "steps": [
                    "Let your arms hang and allow your shoulders to relax.",
                    "Lift your shoulders and gently let them lower 5 times.",
                    "Draw your shoulder blades back and down 6 times.",
                    "Bend your elbows and slowly open your arms 6 times.",
                ],
            },
            {
                "title": "Upper body without tension",
                "eyebrow": "A mix of small movements",
                "duration_seconds": 180,
                "steps": [
                    "Gently draw your chin backwards 5 times.",
                    "Turn your head right and left 3 times within comfort.",
                    "Open your fingers fully and shake out your hands.",
                    "Lower your shoulders, set your shoulder blades 6 times and walk briefly.",
                ],
            },
            {
                "title": "Shoulder blades and open chest",
                "eyebrow": "Calm upper-body reset",
                "duration_seconds": 180,
                "steps": [
                    "Sit with back support and let your arms relax.",
                    "Gently widen across the collarbones and draw the shoulder blades back and down 6 times.",
                    "Draw your chin backwards 5 times while looking ahead.",
                    "Relax your shoulders and walk briefly.",
                ],
            },
            {
                "title": "Micro-movements for neck and shoulders",
                "eyebrow": "No long holds",
                "duration_seconds": 150,
                "steps": [
                    "Sit tall and make 4 gentle chin retractions.",
                    "Turn right and left twice through a small comfortable range.",
                    "Lift and slowly lower your shoulders 5 times.",
                    "Draw your shoulder blades together 5 times and return to neutral.",
                ],
            },
        ],
    },
    "drops": {
        "title": "Eye drops",
        "eyebrow": "Follow your clinician’s schedule",
        "note": "The app only provides timing. Discuss the use of any eye-care product with a clinician.",
        "steps": [
            "Check the product and scheduled time.",
            "Wash your hands and keep the bottle tip away from the eye and lashes.",
            "Close the eye gently afterwards; do not rub it.",
        ],
    },
    "back": {
        "title": "Lower-back movement",
        "eyebrow": "Gentle movement",
        "note": "Stop if symptoms are uncomfortable or worsening. An individual routine is best discussed with a clinician.",
        "steps": [
            "Stand and walk calmly.",
            "Shift weight from side to side while holding support.",
            "Use only a small, comfortable standing range.",
        ],
        "variants": [
            {
                "title": "Walk and change support",
                "eyebrow": "Gentle movement",
                "duration_seconds": 180,
                "steps": [
                    "Walk calmly for about a minute.",
                    "Holding stable support, shift weight side to side 8 times.",
                    "Make 5 very small standing extensions only if comfortable.",
                    "Return to easy walking.",
                ],
            },
            {
                "title": "Let the legs help the back",
                "eyebrow": "Stay near a chair",
                "duration_seconds": 180,
                "steps": [
                    "Do 5 slow sit-to-stands if comfortable.",
                    "Rise onto your toes 8 times while holding support.",
                    "Shift weight from side to side 4 times each way.",
                    "Walk at an easy pace.",
                ],
            },
            {
                "title": "Change posture freely",
                "eyebrow": "No forced stretching",
                "duration_seconds": 180,
                "steps": [
                    "Stand and take a few calm steps.",
                    "Holding a chair, slightly bend and straighten your knees 6 times.",
                    "Take 6 small side steps and return.",
                    "Finish with easy walking.",
                ],
            },
            {
                "title": "Stand up without rushing",
                "eyebrow": "Movement after sitting",
                "duration_seconds": 180,
                "steps": [
                    "Sit near the front of a stable chair with feet on the floor.",
                    "Stand and sit slowly 5 times, using support if needed.",
                    "Rise onto your toes 6 times.",
                    "Walk for the rest of the break.",
                ],
            },
            {
                "title": "Steps in different directions",
                "eyebrow": "Gentle hip and leg activity",
                "duration_seconds": 180,
                "steps": [
                    "Walk for about a minute.",
                    "Holding support, take 4 small side steps and return.",
                    "Shift weight forwards and backwards 4 times without bending deeply.",
                    "Return to normal walking.",
                ],
            },
        ],
    },
    "wrists": {
        "title": "Release the hands",
        "eyebrow": "Gentle hand movement",
        "note": "Do not pull the fingers with the other hand into discomfort. Discuss recurring symptoms with a clinician.",
        "steps": [
            "Lower your arms and gently shake out your hands.",
            "Open and close the fingers slowly.",
            "Move the wrists through a small comfortable range.",
        ],
        "variants": [
            {
                "title": "Open and release the hands",
                "eyebrow": "Free movement",
                "duration_seconds": 90,
                "steps": [
                    "Lower your arms and lightly shake out relaxed hands.",
                    "Open the fingers and form a soft, unforced fist 8 times.",
                    "Make 4 small wrist circles in each direction.",
                ],
            },
            {
                "title": "Change finger shapes",
                "eyebrow": "No forceful stretch",
                "duration_seconds": 90,
                "steps": [
                    "Start with straight relaxed fingers and neutral wrists.",
                    "Bend at the large knuckles, keep fingers straight, then reopen 5 times.",
                    "Make a soft fist and fully reopen 5 times.",
                    "Finish by gently shaking out the hands.",
                ],
            },
            {
                "title": "Wrists and forearms",
                "eyebrow": "Active mobility",
                "duration_seconds": 90,
                "steps": [
                    "Bend the elbows and turn palms up, then down 6 times.",
                    "Without help from the other hand, move the wrists gently up and down 5 times.",
                    "Spread and relax the fingers 6 times.",
                    "Lower the arms and shake out the hands.",
                ],
            },
            {
                "title": "Thumb meets each finger",
                "eyebrow": "Precise finger movement",
                "duration_seconds": 90,
                "steps": [
                    "Keep the wrists neutral and palms relaxed.",
                    "Touch the thumb to each fingertip in turn 3 times.",
                    "Spread the fingers comfortably and relax them 6 times.",
                    "Make a soft fist, reopen and shake out the hands.",
                ],
            },
            {
                "title": "Keyboard reset",
                "eyebrow": "Active movement without pulling",
                "duration_seconds": 90,
                "steps": [
                    "Move your hands away from the keyboard and rest the forearms.",
                    "Gently lift and lower the hands 5 times without using the other hand.",
                    "Turn palms up and down 6 times.",
                    "Open the fingers, relax and shake out the hands.",
                ],
            },
        ],
    },
    "breathing": {
        "title": "Two quieter minutes",
        "eyebrow": "Calm breathing",
        "note": "If you feel dizzy, return to your normal breathing.",
        "steps": [
            "Put both feet on the floor and relax your shoulders.",
            "Breathe gently and naturally.",
            "Do not force a deep breath or hold your breath.",
        ],
        "variants": [
            {
                "title": "Quiet natural breathing",
                "eyebrow": "No forced deep breaths",
                "duration_seconds": 120,
                "steps": [
                    "Sit with back support, feet on the floor and shoulders relaxed.",
                    "Place a hand on the lower ribs and notice their gentle movement.",
                    "Breathe quietly and normally; do not deliberately enlarge the breath.",
                ],
            },
            {
                "title": "A steady easy rhythm",
                "eyebrow": "Gentle counting",
                "duration_seconds": 120,
                "steps": [
                    "Get comfortable and begin with several normal breaths.",
                    "Breathe in gently for about 3 counts and out for about 3 counts.",
                    "After a few cycles, return to natural breathing.",
                ],
            },
            {
                "title": "A slightly longer exhale",
                "eyebrow": "No breath holding",
                "duration_seconds": 120,
                "steps": [
                    "Relax your shoulders and take a few normal breaths.",
                    "If comfortable, breathe in for about 2 counts and out gently for 4.",
                    "Do not push air out; return to normal breathing if uncomfortable.",
                ],
            },
            {
                "title": "A pause without counting",
                "eyebrow": "Simply notice natural breathing",
                "duration_seconds": 120,
                "steps": [
                    "Sit comfortably with both feet on the floor and shoulders relaxed.",
                    "Without changing anything, notice each easy inhale and exhale.",
                    "If the exhale naturally lengthens, allow it without forcing.",
                ],
            },
            {
                "title": "Lower-rib movement",
                "eyebrow": "Gentle breath awareness",
                "duration_seconds": 120,
                "steps": [
                    "Place your hands at the sides of the lower ribs and relax your shoulders.",
                    "Breathe normally and notice the small movement under your hands.",
                    "Remove your hands and finish with several natural breaths.",
                ],
            },
        ],
    },
    "water": {
        "title": "Check your thirst",
        "eyebrow": "No mandatory water target",
        "note": "Do not drink by force; any fluid restriction from a clinician takes priority.",
        "steps": [
            "If you are thirsty, take a few sips of water.",
            "Look away from the screen and change posture at the same time.",
        ],
    },
}


def text(language: str, russian: str) -> str:
    return UI_EN.get(russian, russian) if language == "en" else russian


def reminder_meta(language: str, kind: str, russian: dict[str, Any]) -> dict[str, Any]:
    if language != "en" or kind not in META_EN:
        return russian
    return {**russian, **META_EN[kind]}
